import { CheckCircle2 } from "lucide-react";
import { PageHeading } from "@/components/ui/PageHeading";
import { PrimaryButton } from "@/components/ui/PrimaryButton";
import { updateExpenseStatus } from "@/features/portal/actions";
import type { ExpenseListItem, ExpenseSummary, RentScheduleListItem } from "@/features/portal/types";
import { cx } from "@/lib/cx";
import type { ModalKind, Role } from "@/types";

const categoryTones = ["bg-violet", "bg-lime", "bg-sky-400", "bg-rose-400", "bg-amber-400"];
const emptySummary: ExpenseSummary = { total: 0, paid: 0, outstanding: 0, categories: [] };
const money = new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR" });

export function ExpensesPage({ role, query, records = [], summary = emptySummary, rentSchedules = [], onOpenModal }: { role: Role; query: string; records?: ExpenseListItem[] | undefined; summary?: ExpenseSummary | undefined; rentSchedules?: RentScheduleListItem[] | undefined; onOpenModal: (kind: ModalKind) => void }) {
  const filtered = records.filter((expense) => `${expense.title} ${expense.category} ${expense.status}`.toLowerCase().includes(query.toLowerCase()));
  return (
    <div className="space-y-6">
      <PageHeading eyebrow="Riepilogo economico" title="Spese e affitto" description="Monitora canone, costi ricorrenti e spese straordinarie registrate per l’appartamento." action={role === "owner" ? <div className="flex flex-wrap gap-2"><PrimaryButton onClick={() => onOpenModal("rent")}>Imposta canone</PrimaryButton><PrimaryButton onClick={() => onOpenModal("expense")}>Registra spesa</PrimaryButton></div> : undefined} />
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rentSchedules.map((rent) => <article key={rent.id} className="rounded-[24px] border border-white bg-white p-5 shadow-[0_12px_40px_rgba(15,23,42,.05)]"><p className="text-xs font-bold uppercase tracking-wider text-violet">Canone ricorrente</p><h2 className="mt-2 font-bold">{rent.label}</h2><p className="mt-2 text-2xl font-bold">{money.format(rent.amount)}</p><p className="mt-2 text-xs text-slate-400">Scadenza il giorno {rent.dueDay} · dal {rent.startsAt}{rent.endsAt ? ` al ${rent.endsAt}` : ""}</p></article>)}{!rentSchedules.length && <article className="rounded-[24px] border border-dashed border-slate-300 p-5 text-sm text-slate-400">Nessun canone configurato.</article>}</section>
      <section className="relative overflow-hidden rounded-[30px] bg-ink p-6 text-white sm:p-8"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_center,rgba(217,142,63,.40),transparent_65%)]" /><div className="relative grid gap-8 lg:grid-cols-[1fr_1.2fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Totale registrato</p><p className="mt-3 text-5xl font-bold tracking-[-.06em]">{money.format(summary.total)}</p><p className="mt-3 flex items-center gap-1 text-sm font-semibold text-lime"><CheckCircle2 className="size-4" /> Dati persistenti dell’appartamento</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/[.07] p-4"><p className="text-xs text-slate-400">Pagato</p><p className="mt-1 text-xl font-bold">{money.format(summary.paid)}</p></div><div className="rounded-2xl bg-white/[.07] p-4"><p className="text-xs text-slate-400">Da saldare</p><p className="mt-1 text-xl font-bold text-lime">{money.format(summary.outstanding)}</p></div></div></div></section>
      <div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]">
        <article className="rounded-[28px] bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,.055)]"><h2 className="font-bold">Ripartizione per categoria</h2><p className="mt-1 text-xs text-slate-400">Calcolata sulle voci registrate</p><div className="mt-7 space-y-5">{summary.categories.map((category, index) => <div key={category.label}><div className="mb-2 flex items-center justify-between text-sm"><span className="font-semibold">{category.label}</span><span className="font-bold">{money.format(category.amount)}</span></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={cx("h-full rounded-full", categoryTones[index % categoryTones.length])} style={{ width: `${category.percent}%` }} /></div></div>)}{!summary.categories.length && <p className="rounded-2xl bg-slate-50 p-5 text-center text-xs text-slate-400">Nessuna spesa registrata.</p>}</div></article>
        <section className="overflow-hidden rounded-[28px] bg-white shadow-[0_12px_40px_rgba(15,23,42,.055)]"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Movimenti</h2><p className="mt-1 text-xs text-slate-400">{filtered.length} risultati</p></div><div className="divide-y divide-slate-100">{filtered.map((expense) => <article key={expense.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="text-sm font-bold">{expense.title}</p><p className="mt-1 text-xs text-slate-400">{expense.category}{expense.due ? ` · scadenza ${expense.due}` : ""}</p></div><p className="text-sm font-bold">{money.format(expense.amount)}</p>{role === "owner" ? <form action={updateExpenseStatus} className="flex items-center gap-2"><input type="hidden" name="id" value={expense.id} /><select name="status" defaultValue={expense.statusCode} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-600" aria-label={`Stato di ${expense.title}`}><option value="EXPECTED">Prevista</option><option value="PARTIALLY_PAID">Parziale</option><option value="PAID">Pagata</option><option value="OVERDUE">Scaduta</option></select><button className="rounded-xl bg-ink px-3 py-2 text-xs font-bold text-white">Aggiorna</button></form> : <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{expense.status}</span>}</article>)}{!filtered.length && <p className="p-8 text-center text-sm text-slate-400">Nessuna spesa corrisponde alla ricerca.</p>}</div></section>
      </div>
    </div>
  );
}
