import { Clock3, LockKeyhole, Mail, ShieldCheck, X } from "lucide-react";
import { InvitationManager } from "@/components/invitations/InvitationManager";
import { PageHeading } from "@/components/ui/PageHeading";
import type { ProfileData } from "@/features/portal/types";
import type { Session } from "@/types";
import { updateApartment, updateMembershipStatus } from "@/features/portal/actions";
import { revokeInvitation } from "@/features/invitations/actions";
import { GoogleServicesPanel } from "@/components/google/GoogleServicesPanel";

const emptyData: ProfileData = { apartment: { name: "Appartamento", address: "", city: "" }, members: [], invitations: [], auditEvents: [], google: { configured: false, encryptionConfigured: false, accountLinked: false, credentialLinked: false, calendarGranted: false, gmailGranted: false, calendarEnabled: false, gmailEnabled: false, calendarName: null, lastSyncedAt: null, lastErrorCode: null, recentEmails: [] } };

export function SettingsPage({ session, data = emptyData }: { session: Session; data?: ProfileData }) {
  const owner = session.role === "owner";
  return (
    <div className="space-y-6">
      <PageHeading eyebrow={owner ? "Gestione appartamento" : "Account personale"} title={owner ? "Impostazioni" : "Il tuo profilo"} description={owner ? "Consulta membri, appartamento e sicurezza dell’account." : "Controlla i tuoi dati e la membership assegnata."} />
      <div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]">
        <section className="settings-profile-card rounded-[28px] bg-ink p-6 text-white"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-[20px] bg-violet text-lg font-bold">{session.initials}</span><div><h2 className="text-lg font-bold">{session.name}</h2><p className="mt-1 text-sm text-slate-400">{session.email}</p></div></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="portal-subcard rounded-2xl bg-white/[.07] p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Ruolo assegnato</p><p className="mt-2 text-sm font-bold text-lime">{owner ? "Proprietario" : "Inquilino"}</p></div><div className="portal-subcard rounded-2xl bg-white/[.07] p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Appartamento</p><p className="mt-2 text-sm font-bold text-emerald-300">{data.apartment.name}</p></div></div><p className="mt-5 flex items-start gap-2 text-xs leading-5 text-slate-400"><LockKeyhole className="mt-0.5 size-4 shrink-0 text-lime" /> Il ruolo deriva dalla membership verificata sul server e non può essere modificato dal browser.</p></section>
        <section className="portal-card rounded-[28px] bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,.055)]"><h2 className="font-bold">Sicurezza account</h2><p className="mt-1 text-xs text-slate-400">Controlli già applicati ai flussi locali.</p><div className="mt-5 space-y-3"><div className="portal-subcard flex items-center gap-3 rounded-2xl border border-slate-100 p-3"><span className="grid size-10 place-items-center rounded-2xl bg-slate-100"><Mail className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold">Account email</p><p className="truncate text-xs text-slate-400">{session.email}</p></div><span className="rounded-xl bg-emerald-50 px-3 py-2 text-[10px] font-bold text-emerald-700">Attivo</span></div><div className="portal-subcard flex items-center gap-3 rounded-2xl border border-slate-100 p-3"><span className="grid size-10 place-items-center rounded-2xl bg-slate-100"><ShieldCheck className="size-4" /></span><div className="flex-1"><p className="text-sm font-bold">Sessione e autorizzazioni</p><p className="text-xs text-slate-400">Sessione server-side e filtro per appartamento</p></div><span className="rounded-xl bg-emerald-50 px-3 py-2 text-[10px] font-bold text-emerald-700">Protetta</span></div></div></section>
      </div>
      <GoogleServicesPanel google={data.google} returnPath={`/${owner ? "owner" : "tenant"}/profilo`} />
      {owner && <section className="rounded-[28px] bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,.055)]"><h2 className="font-bold">Dati appartamento</h2><form action={updateApartment} className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs font-bold text-slate-600">Nome<input name="name" required minLength={2} maxLength={120} defaultValue={data.apartment.name} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-normal" /></label><label className="text-xs font-bold text-slate-600">Indirizzo<input name="address" required minLength={3} maxLength={180} defaultValue={data.apartment.address} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-normal" /></label><label className="text-xs font-bold text-slate-600">Città<input name="city" required minLength={2} maxLength={100} defaultValue={data.apartment.city} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-normal" /></label><button className="w-fit rounded-xl bg-ink px-4 py-2 text-xs font-bold text-white sm:col-span-3">Salva dati</button></form></section>}
      {owner && <section className="rounded-[28px] bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,.055)]"><h2 className="font-bold">Invita un inquilino</h2><p className="mt-1 text-xs text-slate-400">Il ruolo viene assegnato dal link personale, valido 7 giorni e utilizzabile una sola volta.</p><InvitationManager />{data.invitations.length > 0 && <div className="mt-5 border-t border-slate-100 pt-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Inviti in attesa</p><div className="mt-2 space-y-2">{data.invitations.map((invitation) => <div key={invitation.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><Mail className="size-4 text-slate-400" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-slate-700">{invitation.email}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-slate-400"><Clock3 className="size-3" /> Scade {invitation.expiresAt}</p></div><form action={revokeInvitation}><input type="hidden" name="id" value={invitation.id} /><button className="grid size-8 place-items-center rounded-lg bg-white text-slate-400 shadow-sm hover:text-rose-600" aria-label={`Revoca invito per ${invitation.email}`}><X className="size-4" /></button></form></div>)}</div></div>}</section>}
      <section className="portal-card rounded-[28px] bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,.055)]"><div><h2 className="font-bold">Membri della casa</h2><p className="mt-1 text-xs text-slate-400">{data.apartment.address}, {data.apartment.city} · {data.members.length} membership</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{data.members.map((member) => <div key={member.id} className="portal-subcard flex items-center gap-3 rounded-2xl border border-slate-100 p-3"><span className="grid size-10 place-items-center rounded-full bg-violet text-xs font-bold text-white">{member.initial}</span><div><p className="text-sm font-bold">{member.name}</p><p className="text-xs text-slate-400">{member.role} · {member.status === "ACTIVE" ? "Attivo" : "Sospeso"}</p></div>{owner && member.role === "Inquilino" ? <form action={updateMembershipStatus} className="ml-auto"><input type="hidden" name="id" value={member.id} /><button name="status" value={member.status === "ACTIVE" ? "SUSPENDED" : "ACTIVE"} className="rounded-xl bg-slate-100 px-3 py-2 text-[10px] font-bold text-slate-600">{member.status === "ACTIVE" ? "Sospendi" : "Riattiva"}</button></form> : <span className={`ml-auto size-2 rounded-full ${member.status === "ACTIVE" ? "bg-emerald-400" : "bg-amber-400"}`} title={member.status} />}</div>)}</div></section>
      {owner && <section className="rounded-[28px] bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,.055)]"><h2 className="font-bold">Audit attività</h2><p className="mt-1 text-xs text-slate-400">Ultime {data.auditEvents.length} operazioni importanti.</p><div className="mt-4 divide-y divide-slate-100">{data.auditEvents.map((event) => <div key={event.id} className="grid gap-1 py-3 text-xs sm:grid-cols-[1fr_.7fr_auto]"><span className="font-bold text-slate-700">{event.action}</span><span className="text-slate-500">{event.actor} · {event.entityType}</span><time className="text-slate-400">{event.date}</time></div>)}{!data.auditEvents.length && <p className="py-5 text-center text-xs text-slate-400">Nessun evento di audit.</p>}</div></section>}
    </div>
  );
}
